/**
 * setupPresets.js
 * Comprehensive ready-to-use page & block templates for every CMS Setup Industry preset:
 * - ecommerce  -> Astra (astra-clean)
 * - digital    -> GeneratePress (generatepress-corp)
 * - agency     -> Kadence WP (kadence-pro)
 * - saas       -> Neve (neve-startup)
 * - rental     -> OceanWP (oceanwp-store)
 * - custom     -> Twenty Twenty-Five (twenty-twenty-five)
 */

export function getIndustryDefaultTheme(industryId) {
  switch (industryId) {
    case 'ecommerce':
      return 'astra-clean';
    case 'digital':
      return 'generatepress-corp';
    case 'agency':
      return 'kadence-pro';
    case 'saas':
      return 'neve-startup';
    case 'rental':
      return 'oceanwp-store';
    case 'custom':
    default:
      return 'twenty-twenty-five';
  }
}

export function getSetupPresetForIndustry(industryType = 'custom', siteIdentity = {}) {
  const year = new Date().getFullYear();

  switch (industryType) {
    case 'ecommerce':
      return {
        id: 'page_home',
        slug: 'home',
        title: siteIdentity.title || 'Store Online Indonesia - Produk Pilihan Berkualitas',
        status: 'published',
        themeId: 'astra-clean',
        colorMode: 'light',
        mobileNavType: 'curved',
        header: {
          brandName: siteIdentity.title || 'Astra Store Online',
          brandTagline: siteIdentity.tagline || 'Koleksi Produk Pilihan Berkualitas & Pengiriman Cepat',
          phone: '0812-3456-7890',
          whatsappNumber: '6281234567890',
          navLinks: [
            { label: 'Beranda', href: '#' },
            { label: 'Koleksi Produk', href: '#fleet' },
            { label: 'Keunggulan', href: '#features' },
            { label: 'Paket Hemat', href: '#pricing' },
            { label: 'Testimoni', href: '#testimonials' },
            { label: 'FAQ', href: '#faq' },
            { label: 'Kontak', href: '/?contact=true' },
          ],
        },
        footer: {
          brandName: siteIdentity.title || 'Astra Store Online',
          description: 'Pusat belanja online terpercaya dengan ribuan koleksi produk berkualitas, jaminan produk original, garansi uang kembali, dan checkout WhatsApp instan.',
          address: 'Sentra Bisnis Grand Mall Blok C-12, Jakarta',
          phone: '0812-3456-7890',
          email: 'cs@astrashop.id',
          copyright: `© ${year} ${siteIdentity.title || 'Astra Store Online'}. Powered by Astra Clean Theme.`,
        },
        floatingWhatsapp: {
          enabled: true,
          phoneNumber: '6281234567890',
          agentName: 'Customer Care 24 Jam',
          agentStatus: 'Online - Siap Melayani',
          greetingMessage: 'Halo! Butuh rekomendasi produk atau ingin order langsung? Tim kami siap melayani Anda.',
          defaultMessage: 'Halo Admin, saya ingin memesan produk di toko online Anda.',
          ctaText: 'Order via WhatsApp',
        },
        seo: {
          metaTitle: `${siteIdentity.title || 'Astra Store Online'} - Belanja Online Mudah & Terpercaya`,
          metaDescription: 'Katalog belanja produk pilihan bergaransi dengan checkout instan dan gratis ongkos kirim seluruh Indonesia.',
          ogImage: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?q=80&w=1600',
          jsonLdType: 'OnlineStore',
          canonical: '',
        },
        blocks: [
          {
            id: 'hero_ecommerce',
            type: 'hero-slider',
            props: {
              badge: 'Koleksi Terbaru • Garansi 100% Original',
              title: 'Gaya Hidup Modern dengan Produk Berkualitas Premium',
              subtitle: 'Temukan tren pakaian, sepatu, dan aksesoris eksklusif pilihan terbaik dengan promo diskon hingga 40% dan gratis ongkos kirim.',
              ctaPrimaryText: 'Belanja Koleksi Sekarang',
              ctaPrimaryLink: '#fleet',
              ctaSecondaryText: 'Chat Admin WhatsApp',
              ctaSecondaryLink: 'https://wa.me/6281234567890',
              slides: [
                {
                  id: 's1',
                  badge: 'Koleksi Musim Baru 2026',
                  title: 'Gaya Hidup Modern dengan Produk Berkualitas Premium',
                  subtitle: 'Temukan tren pakaian, sepatu, dan aksesoris eksklusif pilihan terbaik dengan promo diskon hingga 40% dan gratis ongkos kirim.',
                  imageUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?q=80&w=1600',
                },
                {
                  id: 's2',
                  badge: 'Gratis Ongkir Se-Indonesia',
                  title: 'Pilihan Terbaik untuk Penampilan Percaya Diri Anda',
                  subtitle: 'Jaminan kualitas bahan premium dengan proses kontrol ketat sebelum dikirim ke pintu rumah Anda.',
                  imageUrl: 'https://images.unsplash.com/photo-1472851294608-062f824d29cc?q=80&w=1600',
                },
              ],
            },
          },
          {
            id: 'features_ecommerce',
            type: 'features',
            props: {
              badge: 'Jaminan Belanja Aman',
              title: 'Mengapa Belanja di Toko Kami?',
              subtitle: 'Pengalaman belanja nyaman dengan standar pelayanan konsumen terbaik.',
              items: [
                { icon: 'shield-check', title: '100% Original Terjamin', desc: 'Produk didistribusikan langsung dari produsen resmi bergaransi keaslian.' },
                { icon: 'zap', title: 'Pengiriman Kilat', desc: 'Pesanan sebelum jam 15.00 dikirim hari yang sama dengan nomor resi instan.' },
                { icon: 'award', title: 'Garansi Retur 7 Hari', desc: 'Ukuran tidak pas atau tidak sesuai pesanan? Tukar baru tanpa ribet.' },
                { icon: 'clock', title: 'Layanan Bantuan 24/7', desc: 'Customer service ramah dan sigap melayani via chat WhatsApp kapan saja.' },
              ],
            },
          },
          {
            id: 'catalog_ecommerce',
            type: 'fleet-catalog',
            props: {
              badge: 'Katalog Produk Pilihan',
              title: 'Produk Terlaris Minggu Ini',
              subtitle: 'Koleksi paling diminati dengan ulasan kepuasan pelanggan tertinggi.',
              catalogType: 'ecommerce',
              items: [
                {
                  id: 'p1',
                  name: 'Urban Street Sneaker Pro',
                  brand: 'Footwear Collection',
                  category: 'Sepatu',
                  pricePerDay: 'Rp 389.000',
                  year: '2026',
                  transmission: 'Original',
                  fuel: 'In-Stock',
                  capacity: 'Size 39-44',
                  rating: 4.9,
                  reviewsCount: 142,
                  image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80',
                  highlight: 'Best Seller',
                  features: ['Bahan Mesh Bernapas', 'Insole Ortholite Empuk', 'Outsole Anti-Slip', 'Bonus Kaos Kaki'],
                },
                {
                  id: 'p2',
                  name: 'Windbreaker Jacket All-Weather',
                  brand: 'Outerwear Apparel',
                  category: 'Pakaian',
                  pricePerDay: 'Rp 299.000',
                  year: '2026',
                  transmission: 'Waterproof',
                  fuel: 'In-Stock',
                  capacity: 'Size S-XXL',
                  rating: 4.8,
                  reviewsCount: 98,
                  image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&auto=format&fit=crop&q=80',
                  highlight: 'Diskon 25%',
                  features: ['Tahan Angin & Air Ringan', 'Saku Dalam Rahasia', 'Resleting YKK Tahan Lama', 'Hoodie Lepas Pasang'],
                },
                {
                  id: 'p3',
                  name: 'Executive Minimalist Watch',
                  brand: 'Chrono Timepiece',
                  category: 'Aksesoris',
                  pricePerDay: 'Rp 450.000',
                  year: '2026',
                  transmission: 'Japan Quartz',
                  fuel: 'In-Stock',
                  capacity: 'Water Resist 5ATM',
                  rating: 5.0,
                  reviewsCount: 215,
                  image: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=600&auto=format&fit=crop&q=80',
                  highlight: 'Edisi Terbatas',
                  features: ['Strap Kulit Asli', 'Kaca Sapphire Anti Gores', 'Water Resistant 50M', 'Kotak Eksklusif Kayu'],
                },
                {
                  id: 'p4',
                  name: 'Canvas Commuter Backpack 22L',
                  brand: 'Gear Carry',
                  category: 'Tas',
                  pricePerDay: 'Rp 275.000',
                  year: '2026',
                  transmission: 'Water Repellent',
                  fuel: 'In-Stock',
                  capacity: 'Slot Laptop 15.6"',
                  rating: 4.9,
                  reviewsCount: 77,
                  image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop&q=80',
                  highlight: 'Populer',
                  features: ['Bahan Kanvas Cordura', 'Kompartemen Laptop Empuk', 'Port Charger USB Terpadu', 'Tali Bahu Ergonomis'],
                },
                {
                  id: 'p5',
                  name: 'Oxford Casual Linen Shirt',
                  brand: 'Modern Classic',
                  category: 'Pakaian',
                  pricePerDay: 'Rp 220.000',
                  year: '2026',
                  transmission: '100% Linen',
                  fuel: 'In-Stock',
                  capacity: 'Size M-XL',
                  rating: 4.7,
                  reviewsCount: 64,
                  image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&auto=format&fit=crop&q=80',
                  highlight: 'Adem Nyaman',
                  features: ['100% Serat Linen Asli', 'Kerah Button-Down Rapi', 'Potongan Modern Regular', 'Tidak Mudah Kusut'],
                },
                {
                  id: 'p6',
                  name: 'Handcrafted Bifold Leather Wallet',
                  brand: 'Artisan Goods',
                  category: 'Aksesoris',
                  pricePerDay: 'Rp 180.000',
                  year: '2026',
                  transmission: 'Kulit Sapi Asli',
                  fuel: 'In-Stock',
                  capacity: '8 Slot Kartu',
                  rating: 4.9,
                  reviewsCount: 112,
                  image: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=600&auto=format&fit=crop&q=80',
                  highlight: 'Handmade',
                  features: ['Kulit Asli Crazy Horse', 'RFID Protection', 'Jahitan Tangan Kokoh', 'Makin Lama Makin Antik'],
                },
              ],
            },
          },
          {
            id: 'pricing_ecommerce',
            type: 'pricing',
            props: {
              badge: 'Paket Hemat Bundling',
              title: 'Pilihan Paket Belanja Lebih Hemat',
              subtitle: 'Beli lebih banyak untuk mendapatkan potongan harga dan bonus merchandise.',
              plans: [
                {
                  name: 'Paket Single',
                  price: 'Rp 249.000',
                  period: '/item',
                  description: 'Satu produk pilihan dengan bonus kemasan proteksi ekstra.',
                  highlight: false,
                  features: ['1 Item Original Pilihan', 'Gratis Ongkir Pulau Jawa', 'Voucher Cashback 5%'],
                  buttonText: 'Beli Paket Single',
                },
                {
                  name: 'Paket Duo Combo',
                  price: 'Rp 459.000',
                  period: '/2 items',
                  description: 'Paling diminati! Hemat Rp 50.000 untuk pembelian sepasang.',
                  highlight: true,
                  features: ['2 Item Pilihan Bebas', 'Gratis Ongkir Se-Indonesia', 'Pouch Eksklusif Gratis', 'Voucher Cashback 10%'],
                  buttonText: 'Beli Paket Duo',
                },
                {
                  name: 'Paket Grosir / Reseller',
                  price: 'Rp 899.000',
                  period: '/5 items',
                  description: 'Harga grosir terbaik untuk kebutuhan keluarga atau dijual kembali.',
                  highlight: false,
                  features: ['5 Item Pilihan', 'Harga Grosir Diskon 30%', 'Prioritas Pengiriman Kilat', 'Grup Komunitas Reseller'],
                  buttonText: 'Beli Paket Grosir',
                },
              ],
            },
          },
          {
            id: 'testimonials_ecommerce',
            type: 'testimonials',
            props: {
              badge: 'Testimoni Pembeli',
              title: 'Ulasan Bintang 5 dari Pelanggan Kami',
              subtitle: 'Ribuan pelanggan puas dengan kualitas barang dan kecepatan layanan kami.',
              reviews: [
                {
                  name: 'Clarissa Natalia',
                  role: 'Verified Buyer - Jakarta',
                  rating: 5,
                  comment: 'Barang sampai hanya dalam 1 hari! Kualitas bahannya luar biasa dan jahitan sangat rapi. Pasti order lagi di sini.',
                  avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&h=100&fit=crop',
                },
                {
                  name: 'Dimas Wicaksono',
                  role: 'Verified Buyer - Surabaya',
                  rating: 5,
                  comment: 'Pelayanan via WhatsApp sangat cepat dan ramah. Saat tanya rekomendasi ukuran langsung dijawab dengan detail.',
                  avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&h=100&fit=crop',
                },
                {
                  name: 'Reza Fahrezi',
                  role: 'Verified Buyer - Bandung',
                  rating: 5,
                  comment: 'Sangat puas dengan pengemasannya yang super aman menggunakan bubble wrap tebal. Barangnya 100% original.',
                  avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100&h=100&fit=crop',
                },
              ],
            },
          },
          {
            id: 'faq_ecommerce',
            type: 'faq',
            props: {
              badge: 'Informasi Belanja',
              title: 'Pertanyaan Seputar Pemesanan & Pembayaran',
              subtitle: 'Ketahui alur checkout mudah dan jaminan keamanan berbelanja.',
              faqs: [
                {
                  q: 'Bagaimana cara memesan produk di toko ini?',
                  a: 'Cukup klik tombol "Pesan via WhatsApp" pada produk yang Anda inginkan. Detail pesanan akan langsung terisi dan terhubung ke admin kami.',
                },
                {
                  q: 'Metode pembayaran apa saja yang didukung?',
                  a: 'Kami menerima transfer bank resmi (BCA, Mandiri, BNI), QRIS instan seluruh e-wallet (GoPay, OVO, ShopeePay), dan opsi COD (bayar di tempat).',
                },
                {
                  q: 'Apakah bisa melakukan penukaran barang jika ukuran tidak pas?',
                  a: 'Tentu bisa! Anda dapat melakukan penukaran ukuran dalam waktu maksimal 7 hari setelah barang diterima dengan menghubungi customer service kami.',
                },
              ],
            },
          },
          {
            id: 'cta_ecommerce',
            type: 'cta',
            props: {
              badge: 'Promo Terbatas Minggu Ini',
              title: 'Klaim Voucher Diskon Anda Sekarang Sebelum Kehabisan!',
              subtitle: 'Stok terbatas untuk promo periode minggu ini. Chat admin kami untuk klaim voucher potongan harga langsung.',
              buttonText: 'Order Cepat via WhatsApp',
              buttonLink: 'https://wa.me/6281234567890',
            },
          },
        ],
      };

    case 'digital':
      return {
        id: 'page_home',
        slug: 'home',
        title: siteIdentity.title || 'Studio Desain & Digital Assets - Premium UI Kits',
        status: 'published',
        themeId: 'generatepress-corp',
        colorMode: 'light',
        mobileNavType: 'curved',
        header: {
          brandName: siteIdentity.title || 'DesignForge Digital',
          brandTagline: siteIdentity.tagline || 'Template UI, Ilustrasi Vektor & Aset Grafis Eksklusif',
          phone: '0812-3456-7890',
          whatsappNumber: '6281234567890',
          navLinks: [
            { label: 'Katalog Aset', href: '#fleet' },
            { label: 'Keunggulan', href: '#features' },
            { label: 'Lisensi & Harga', href: '#pricing' },
            { label: 'Ulasan Desainer', href: '#testimonials' },
            { label: 'FAQ', href: '#faq' },
            { label: 'Kontak', href: '/?contact=true' },
          ],
        },
        footer: {
          brandName: siteIdentity.title || 'DesignForge Digital',
          description: 'Pusat unduh aset desain digital kelas dunia. UI kits, ilustrasi 3D, mockup presentasi, dan library komponen siap produksi untuk desainer dan tim produk.',
          address: 'Creative Tech Hub Lt. 5, Jl. Senopati No. 88, Jakarta Selatan',
          phone: '0812-3456-7890',
          email: 'support@designforge.id',
          copyright: `© ${year} ${siteIdentity.title || 'DesignForge Digital'}. Powered by GeneratePress Theme.`,
        },
        floatingWhatsapp: {
          enabled: true,
          phoneNumber: '6281234567890',
          agentName: 'Studio Support',
          agentStatus: 'Online',
          greetingMessage: 'Halo! Butuh bantuan lisensi atau kustomisasi aset UI?',
          defaultMessage: 'Halo Admin, saya ingin bertanya seputar aset digital dan lisensi komersial.',
          ctaText: 'Chat Studio Support',
        },
        seo: {
          metaTitle: `${siteIdentity.title || 'DesignForge Digital'} - Download UI Kit & Aset Grafis`,
          metaDescription: 'Download template UI Figma berstandar internasional, icon pack 3D, dan aset vektor komersial siap pakai.',
          ogImage: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?q=80&w=1600',
          jsonLdType: 'SoftwareApplication',
          canonical: '',
        },
        blocks: [
          {
            id: 'hero_digital',
            type: 'hero-slider',
            props: {
              badge: 'Tema Resmi GeneratePress • Digital Assets',
              title: 'Percepat Workflow Desain dengan UI Kit Standar Industri',
              subtitle: 'Koleksi lengkap template Figma, aset 3D siap render, dan sistem desain modular yang dirancang untuk mempercepat peluncuran produk digital Anda.',
              ctaPrimaryText: 'Jelajahi Semua Aset',
              ctaPrimaryLink: '#fleet',
              ctaSecondaryText: 'Lihat Paket Lisensi',
              ctaSecondaryLink: '#pricing',
              slides: [
                {
                  id: 's1',
                  badge: 'Figma UI Kit & Web Component Library 2026',
                  title: 'Percepat Workflow Desain dengan UI Kit Standar Industri',
                  subtitle: 'Koleksi lengkap template Figma, aset 3D siap render, dan sistem desain modular yang dirancang untuk mempercepat peluncuran produk digital Anda.',
                  imageUrl: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?q=80&w=1600',
                },
              ],
            },
          },
          {
            id: 'features_digital',
            type: 'features',
            props: {
              badge: 'Standar Kualitas Aset',
              title: 'Keunggulan Menggunakan Aset DesignForge',
              subtitle: 'Dibuat dengan presisi tinggi oleh desainer produk senior dari industri global.',
              items: [
                { icon: 'shield-check', title: 'Auto-Layout & Variabel Figma', desc: '100% menggunakan fitur terbaru Figma dengan dukungan mode terang dan gelap siap pakai.' },
                { icon: 'zap', title: 'Unduh Instan Setelah Checkout', desc: 'Akses link unduhan langsung dikirim ke email dan WhatsApp Anda dalam hitungan detik.' },
                { icon: 'award', title: 'Lisensi Komersial Bebas Royalti', desc: 'Gunakan bebas untuk proyek pribadi, klien agensi, maupun startup komersial.' },
                { icon: 'clock', title: 'Update Seumur Hidup Gratis', desc: 'Dapatkan revisi dan penambahan komponen baru secara berkala tanpa biaya tambahan.' },
              ],
            },
          },
          {
            id: 'catalog_digital',
            type: 'fleet-catalog',
            props: {
              badge: 'Katalog Produk Digital',
              title: 'Aset Desain Paling Diminati',
              subtitle: 'Pilihan template dan UI Kit yang telah digunakan oleh lebih dari 5.000 tim produk.',
              catalogType: 'digital',
              items: [
                {
                  id: 'd1',
                  name: 'Nova SaaS Design System Pro',
                  brand: 'DesignForge',
                  category: 'UI Kit',
                  pricePerDay: 'Rp 499.000',
                  year: '2026',
                  transmission: 'Figma .FIG',
                  fuel: 'Lisensi Komersial',
                  capacity: '400+ Components',
                  rating: 5.0,
                  reviewsCount: 88,
                  image: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=600&auto=format&fit=crop&q=80',
                  highlight: 'Trending #1',
                  features: ['400+ Komponen Auto-Layout', 'Design Tokens & Variables', '15 Contoh Layar Siap Pakai', 'Dokumentasi Lengkap'],
                },
                {
                  id: 'd2',
                  name: '3D Isometric Tech Icon Pack',
                  brand: 'DesignForge 3D',
                  category: 'Aset 3D',
                  pricePerDay: 'Rp 199.000',
                  year: '2026',
                  transmission: 'PNG + Blender',
                  fuel: 'Resolusi 4K',
                  capacity: '80+ 3D Assets',
                  rating: 4.9,
                  reviewsCount: 65,
                  image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
                  highlight: 'High Res 4K',
                  features: ['80 Aset 3D Unik', 'Format PNG Transparan 4K', 'File Sumber Blender (.blend)', 'Pencahayaan Studio Siap Pakai'],
                },
                {
                  id: 'd3',
                  name: 'Fintech Mobile App Wireframe',
                  brand: 'AppFlow Studio',
                  category: 'Wireframe',
                  pricePerDay: 'Rp 299.000',
                  year: '2026',
                  transmission: 'Figma + XD',
                  fuel: 'Lisensi Tim',
                  capacity: '65 Screens',
                  rating: 4.8,
                  reviewsCount: 42,
                  image: 'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=600&auto=format&fit=crop&q=80',
                  highlight: 'Terlengkap',
                  features: ['65 Alur Layar Lengkap', 'User Flow Diagram Terpadu', 'Kompatibel iOS & Android', 'Mudah Dikustomisasi'],
                },
                {
                  id: 'd4',
                  name: 'Minimalist Brand Identity Mockups',
                  brand: 'Studio Print',
                  category: 'Mockup',
                  pricePerDay: 'Rp 249.000',
                  year: '2026',
                  transmission: 'Photoshop PSD',
                  fuel: 'Smart Object',
                  capacity: '18 Mockups',
                  rating: 4.9,
                  reviewsCount: 53,
                  image: 'https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?w=600&auto=format&fit=crop&q=80',
                  highlight: 'Photorealistic',
                  features: ['18 Scene Mockup Realistis', 'Edit Mudah via Smart Object', 'Tekstur Kertas Alami', 'Resolusi Tajam 5000px'],
                },
                {
                  id: 'd5',
                  name: 'Executive Pitch Deck Presentation',
                  brand: 'VentureSlide',
                  category: 'Slide',
                  pricePerDay: 'Rp 179.000',
                  year: '2026',
                  transmission: 'PPTX + Figma',
                  fuel: '16:9 HD',
                  capacity: '50 Slides',
                  rating: 4.9,
                  reviewsCount: 79,
                  image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&auto=format&fit=crop&q=80',
                  highlight: 'Investor Ready',
                  features: ['50 Slide Berstandar Silicon Valley', 'Grafik & Diagram Editable', 'Format PowerPoint & Google Slides', 'Tipografi Modern Bersih'],
                },
                {
                  id: 'd6',
                  name: 'Developer Portfolio Web Template',
                  brand: 'CodeCraft',
                  category: 'Template Web',
                  pricePerDay: 'Rp 349.000',
                  year: '2026',
                  transmission: 'React + HTML5',
                  fuel: 'Tailwind CSS',
                  capacity: 'Responsive',
                  rating: 5.0,
                  reviewsCount: 91,
                  image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=600&auto=format&fit=crop&q=80',
                  highlight: 'Clean Code',
                  features: ['Kode React & Tailwind Bersih', 'Skor Lighthouse 100', 'SEO Teroptimasi', 'Deploy Instan ke Vercel/Netlify'],
                },
              ],
            },
          },
          {
            id: 'pricing_digital',
            type: 'pricing',
            props: {
              badge: 'Lisensi Fleksibel',
              title: 'Pilihan Lisensi Sesuai Kebutuhan Tim',
              subtitle: 'Investasi terbaik dengan hak cipta penggunaan komersial resmi tanpa batasan proyek.',
              plans: [
                {
                  name: 'Personal License',
                  price: 'Rp 199.000',
                  period: '/aset',
                  description: 'Ideal untuk freelancer, desainer mandiri, dan portofolio pribadi.',
                  highlight: false,
                  features: ['1 Pengguna / Desainer', '1 Proyek Pribadi atau Klien', 'File Sumber Figma Lengkap', 'Update Aset 1 Tahun'],
                  buttonText: 'Pilih Lisensi Personal',
                },
                {
                  name: 'Commercial Pro',
                  price: 'Rp 599.000',
                  period: '/bundle',
                  description: 'Paling diminati! Untuk agensi dan tim desain dengan banyak klien.',
                  highlight: true,
                  features: ['Hingga 5 Anggota Tim', 'Proyek Klien Tanpa Batas', 'Akses Semua File Sumber & 3D', 'Update Seumur Hidup Gratis', 'Prioritas Support Desain'],
                  buttonText: 'Pilih Lisensi Komersial',
                },
                {
                  name: 'Extended Enterprise',
                  price: 'Rp 1.499.000',
                  period: '/unlimited',
                  description: 'Akses penuh tanpa batas untuk korporasi, SaaS, dan studio produk.',
                  highlight: false,
                  features: ['Pengguna Tidak Terbatas', 'Distribusi dalam Produk SaaS', 'Custom Branding & Token', 'Dedicated Support Manager', 'Perjanjian Lisensi Resmi'],
                  buttonText: 'Pilih Extended License',
                },
              ],
            },
          },
          {
            id: 'testimonials_digital',
            type: 'testimonials',
            props: {
              badge: 'Ulasan Profesional',
              title: 'Apa Kata Para Desainer Produk?',
              subtitle: 'Tanggapan dari UI/UX designer, startup founder, dan art director.',
              reviews: [
                {
                  name: 'Bima Satria',
                  role: 'Lead Product Designer di FinTech Startup',
                  rating: 5,
                  comment: 'Nova UI Kit sangat terstruktur. Struktur token dan variasi autolayout-nya menghemat setidaknya 3 minggu kerja tim kami.',
                  avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&h=100&fit=crop',
                },
                {
                  name: 'Nadia Putri',
                  role: 'Freelance UI/UX Designer',
                  rating: 5,
                  comment: 'Kualitas aset 3D-nya sangat tajam! Klien saya langsung terkesima saat presentasi landing page pertama kali.',
                  avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&h=100&fit=crop',
                },
                {
                  name: 'Fauzi Rahman',
                  role: 'Creative Director di Media Studio',
                  rating: 5,
                  comment: 'GeneratePress Theme sangat ringan dan mudah dikustomisasi. Landing page produk digital kami memuat dalam sekejap.',
                  avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=100&h=100&fit=crop',
                },
              ],
            },
          },
          {
            id: 'faq_digital',
            type: 'faq',
            props: {
              badge: 'FAQ Lisensi',
              title: 'Pertanyaan Seputar Download & Lisensi Aset',
              subtitle: 'Pelajari hak penggunaan dan proses pengunduhan file digital Anda.',
              faqs: [
                {
                  q: 'Format file apa saja yang akan saya dapatkan setelah checkout?',
                  a: 'Anda akan mendapatkan link unduhan langsung berisi file Figma (.fig), format PNG resolusi tinggi (4K), aset vektor SVG, serta file 3D Blender (.blend).',
                },
                {
                  q: 'Bolehkah saya menggunakan aset ini untuk proyek berbayar klien?',
                  a: 'Ya! Lisensi Commercial Pro dan Extended Enterprise membolehkan Anda menggunakan seluruh aset dalam proyek klien berbayar tanpa batasan.',
                },
                {
                  q: 'Apakah ada update jika ada versi baru Figma?',
                  a: 'Tentu. Kami rutin memperbarui file komponen saat Figma merilis pembaruan fitur, dan Anda dapat mengunduh versi terbaru secara gratis.',
                },
              ],
            },
          },
          {
            id: 'cta_digital',
            type: 'cta',
            props: {
              badge: 'Akses Lengkap All-In-One',
              title: 'Mulai Rancang Produk Hebat Anda Hari Ini',
              subtitle: 'Dapatkan seluruh koleksi UI Kit, icon pack 3D, dan template presentasi dengan harga promo khusus.',
              buttonText: 'Beli Paket Komplit via WhatsApp',
              buttonLink: 'https://wa.me/6281234567890',
            },
          },
        ],
      };

    case 'agency':
      return {
        id: 'page_home',
        slug: 'home',
        title: siteIdentity.title || 'Creative Agency & Studio - Brand & Digital Experience',
        status: 'published',
        themeId: 'kadence-pro',
        colorMode: 'light',
        mobileNavType: 'curved',
        header: {
          brandName: siteIdentity.title || 'Kadence Creative Studio',
          brandTagline: siteIdentity.tagline || 'Membangun Identitas Brand & Pengalaman Digital Kelas Dunia',
          phone: '0812-3456-7890',
          whatsappNumber: '6281234567890',
          navLinks: [
            { label: 'Portofolio', href: '#fleet' },
            { label: 'Layanan', href: '#features' },
            { label: 'Paket Kerjasama', href: '#pricing' },
            { label: 'Klien & Ulasan', href: '#testimonials' },
            { label: 'FAQ', href: '#faq' },
            { label: 'Konsultasi', href: '/?contact=true' },
          ],
        },
        footer: {
          brandName: siteIdentity.title || 'Kadence Creative Studio',
          description: 'Studio desain dan agensi strategi digital yang membantu para founder dan eksekutif membangun brand masa depan dengan estetika luar biasa dan eksekusi presisi.',
          address: 'District 8 SCBD Tower Treasury Lt. 21, Jakarta Selatan',
          phone: '0812-3456-7890',
          email: 'hello@kadencestudio.com',
          copyright: `© ${year} ${siteIdentity.title || 'Kadence Creative Studio'}. Powered by Kadence WP Theme.`,
        },
        floatingWhatsapp: {
          enabled: true,
          phoneNumber: '6281234567890',
          agentName: 'Client Relationship Partner',
          agentStatus: 'Online',
          greetingMessage: 'Halo! Ingin mendiskusikan visi proyek brand atau website baru Anda?',
          defaultMessage: 'Halo Tim Agensi, saya ingin konsultasi proyek desain brand & web development.',
          ctaText: 'Konsultasi Partner Lead',
        },
        seo: {
          metaTitle: `${siteIdentity.title || 'Kadence Creative Studio'} - Agensi Desain & Brand Digital`,
          metaDescription: 'Agensi kreatif terkemuka di Jakarta yang melayani strategi identitas brand, desain UI/UX kelas dunia, dan pengembangan web modern.',
          ogImage: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?q=80&w=1600',
          jsonLdType: 'ProfessionalService',
          canonical: '',
        },
        blocks: [
          {
            id: 'hero_agency',
            type: 'hero-slider',
            props: {
              badge: 'Tema Resmi Kadence WP • Agensi Kreatif & Portofolio',
              title: 'Membangun Identitas Brand & Pengalaman Digital Masa Depan',
              subtitle: 'Kami memadukan strategi narasi brand mendalam dengan keahlian rekayasa web modern untuk menciptakan produk digital yang dicintai audiens Anda.',
              ctaPrimaryText: 'Lihat Showcase Portofolio',
              ctaPrimaryLink: '#fleet',
              ctaSecondaryText: 'Jadwalkan Sesi Konsultasi',
              ctaSecondaryLink: '/?contact=true',
              slides: [
                {
                  id: 's1',
                  badge: 'Desain Bermakna • Dampak Nyata',
                  title: 'Membangun Identitas Brand & Pengalaman Digital Masa Depan',
                  subtitle: 'Kami memadukan strategi narasi brand mendalam dengan keahlian rekayasa web modern untuk menciptakan produk digital yang dicintai audiens Anda.',
                  imageUrl: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?q=80&w=1600',
                },
              ],
            },
          },
          {
            id: 'features_agency',
            type: 'features',
            props: {
              badge: 'Keahlian & Layanan Studio',
              title: 'Solusi Kreatif Menyeluruh dari Hati',
              subtitle: 'Setiap karya dikerjakan dengan standar kesempurnaan tertinggi untuk membedakan brand Anda dari kompetisi.',
              items: [
                { icon: 'shield-check', title: 'Brand Identity & Strategy', desc: 'Merumuskan visi, positioning pasar, tone of voice, dan panduan identitas visual yang ikonik.' },
                { icon: 'zap', title: 'High-End Web Development', desc: 'Membangun situs web performa tinggi dengan arsitektur modern, animasi mulus, dan SEO terdepan.' },
                { icon: 'award', title: 'UI/UX Product Design', desc: 'Riset pengguna mendalam dan prototipe interaktif yang fokus pada kemudahan konversi.' },
                { icon: 'clock', title: 'Growth & Creative Retainer', desc: 'Dukungan berkelanjutan untuk menjaga brand Anda selalu segar, relevan, dan dinamis.' },
              ],
            },
          },
          {
            id: 'catalog_agency',
            type: 'fleet-catalog',
            props: {
              badge: 'Showcase Karya Pilihan',
              title: 'Proyek Terkini yang Kami Banggakan',
              subtitle: 'Jelajahi hasil kolaborasi kami dengan berbagai brand visioner dan perusahaan terdepan.',
              catalogType: 'digital',
              items: [
                {
                  id: 'w1',
                  name: 'FinPulse - Fintech Mobile App Redesign',
                  brand: 'Fintech Corp',
                  category: 'UI/UX Design',
                  pricePerDay: 'Studi Kasus',
                  year: '2026',
                  transmission: 'Mobile App',
                  fuel: 'Impact: +140% Conversion',
                  capacity: 'Fintech & Wealth',
                  rating: 5.0,
                  reviewsCount: 34,
                  image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&auto=format&fit=crop&q=80',
                  highlight: 'Penghargaan Desain',
                  features: ['Riset Pengguna 50+ Responden', 'Design System Khusus Fintech', 'Micro-Interactions Animasi', 'Peningkatan Retensi Pengguna'],
                },
                {
                  id: 'w2',
                  name: 'Aethelgard - Luxury Artisan Fashion Brand',
                  brand: 'Aethelgard Studio',
                  category: 'Branding',
                  pricePerDay: 'Studi Kasus',
                  year: '2026',
                  transmission: 'Full Identity',
                  fuel: 'Luxury Goods',
                  capacity: 'Brand Guideline',
                  rating: 5.0,
                  reviewsCount: 28,
                  image: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=600&auto=format&fit=crop&q=80',
                  highlight: 'Visual Identity',
                  features: ['Logo & Tipografi Kustom', 'Desain Kemasan Ramah Lingkungan', 'Lookbook Editorial Digital', 'Pedoman Identitas Lengkap'],
                },
                {
                  id: 'w3',
                  name: 'Kroma - Enterprise SaaS Web Platform',
                  brand: 'Kroma AI',
                  category: 'Web Development',
                  pricePerDay: 'Studi Kasus',
                  year: '2026',
                  transmission: 'React & CMS',
                  fuel: 'Lighthouse 99',
                  capacity: 'Global Audience',
                  rating: 4.9,
                  reviewsCount: 45,
                  image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&auto=format&fit=crop&q=80',
                  highlight: 'High Performance',
                  features: ['Kecepatan Loading Sub-Second', 'Integrasi CMS Dinamis', 'Multi-Language Support', 'Peringkat #1 SEO Organik'],
                },
                {
                  id: 'w4',
                  name: 'Solaria - Smart Home IoT Ecosystem',
                  brand: 'Solaria Labs',
                  category: 'UI/UX Design',
                  pricePerDay: 'Studi Kasus',
                  year: '2026',
                  transmission: 'IoT Controller',
                  fuel: 'Smart Hardware',
                  capacity: 'Mobile & Tablet',
                  rating: 5.0,
                  reviewsCount: 19,
                  image: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=600&auto=format&fit=crop&q=80',
                  highlight: 'IoT Experience',
                  features: ['Dashboard Kontrol Perangkat Terpadu', 'Latency Rendah Real-Time UI', 'Mode Terang & Gelap Adaptif', 'User Accessibility Friendly'],
                },
                {
                  id: 'w5',
                  name: 'Terra Botanica - Sustainable Coffee & Tea',
                  brand: 'Terra Organics',
                  category: 'Branding',
                  pricePerDay: 'Studi Kasus',
                  year: '2026',
                  transmission: 'Packaging & Web',
                  fuel: 'Eco Lifestyle',
                  capacity: 'Global Export',
                  rating: 4.9,
                  reviewsCount: 31,
                  image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=80',
                  highlight: 'Eco Packaging',
                  features: ['Desain Kemasan Kompos Organik', 'E-Commerce Storefront Terintegrasi', 'Cerita Asal Usul Petani Kopi', 'Fotografi Produk Konseptual'],
                },
                {
                  id: 'w6',
                  name: 'VentureHorizon - Venture Capital Portal',
                  brand: 'VH Capital',
                  category: 'Web Development',
                  pricePerDay: 'Studi Kasus',
                  year: '2026',
                  transmission: 'Portal Investor',
                  fuel: 'Enterprise Grade',
                  capacity: 'Private Equity',
                  rating: 5.0,
                  reviewsCount: 22,
                  image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600&auto=format&fit=crop&q=80',
                  highlight: 'Executive Portal',
                  features: ['Portal Akses Data Portofolio', 'Enkripsi Data Tingkat Bank', 'Desain Minimalis Berwibawa', 'Optimasi Layar Sentuh Tablet'],
                },
              ],
            },
          },
          {
            id: 'pricing_agency',
            type: 'pricing',
            props: {
              badge: 'Pilihan Kerjasama',
              title: 'Paket Kolaborasi Investasi Brand',
              subtitle: 'Transparansi anggaran dengan scope kerja terukur dan hasil berkualitas tinggi.',
              plans: [
                {
                  name: 'Brand Strategy Sprint',
                  price: 'Rp 7.500.000',
                  period: '/proyek',
                  description: 'Fondasi kuat identitas visual untuk peluncuran bisnis atau produk baru.',
                  highlight: false,
                  features: ['Workshop Visi & Brand Archetype', 'Desain Logo Utama & Sistem Simbol', 'Panduan Palet Warna & Tipografi', 'File Master Vektor Siap Cetak'],
                  buttonText: 'Pilih Brand Sprint',
                },
                {
                  name: 'Full Web & Experience',
                  price: 'Rp 18.000.000',
                  period: '/proyek',
                  description: 'Paling populer! Website kustom kelas dunia dengan CMS terintegrasi.',
                  highlight: true,
                  features: ['Semua Fitur Brand Sprint', 'Desain UI/UX Kustom Responsive', 'Pengembangan CMS Ultra-Fast', 'Optimasi SEO On-Page Lengkap', 'Dukungan Maintenance 60 Hari'],
                  buttonText: 'Pilih Web Experience',
                },
                {
                  name: 'Dedicated Growth Retainer',
                  price: 'Rp 35.000.000',
                  period: '/bulan',
                  description: 'Tim kreatif senior bertindak sebagai divisi desain in-house brand Anda.',
                  highlight: false,
                  features: ['Dukungan Tim Kreatif Lengkap', 'Iterasi Desain & Fitur Tanpa Batas', 'Sprint Mingguan & Review Direksi', 'Prioritas Pengerjaan 24 Jam', 'SLA Respon Kilat 1 Jam'],
                  buttonText: 'Hubungi Lead Partner',
                },
              ],
            },
          },
          {
            id: 'testimonials_agency',
            type: 'testimonials',
            props: {
              badge: 'Kata Mitra Kami',
              title: 'Pengalaman Bekerja Sama dengan Kadence Studio',
              subtitle: 'Kepercayaan dari para founder dan eksekutif perusahaan terkemuka.',
              reviews: [
                {
                  name: 'Handoko Wibowo',
                  role: 'CEO FinPulse Technologies',
                  rating: 5,
                  comment: 'Kadence Studio bukan sekadar desainer biasa, mereka benar-benar memahami logika bisnis kami. Peluncuran produk kami sukses besar.',
                  avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
                },
                {
                  name: 'Elena Rostova',
                  role: 'CMO Aethelgard Fashion',
                  rating: 5,
                  comment: 'Sentuhan artistik mereka luar biasa. Estetika yang mereka bangun untuk brand kami langsung dipuji oleh buyer internasional.',
                  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop',
                },
                {
                  name: 'Taufik Hidayat',
                  role: 'Managing Partner VentureHorizon',
                  rating: 5,
                  comment: 'Profesionalisme tinggi, komunikasi transparan, dan delivery tepat waktu. Sangat merekomendasikan untuk proyek skala korporat.',
                  avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop',
                },
              ],
            },
          },
          {
            id: 'faq_agency',
            type: 'faq',
            props: {
              badge: 'Tanya Jawab Kemitraan',
              title: 'Hal yang Sering Ditanyakan Klien Kami',
              subtitle: 'Memahami proses kerja, timeline, dan alur kolaborasi studio kami.',
              faqs: [
                {
                  q: 'Berapa lama rata-rata waktu pengerjaan proyek website dan brand?',
                  a: 'Untuk paket Brand Strategy Sprint memakan waktu 2-3 minggu. Sedangkan untuk pembuatan website komprehensif memakan waktu antara 4 hingga 8 minggu.',
                },
                {
                  q: 'Apakah tim kami akan mendapatkan sesi konsultasi berkala?',
                  a: 'Tentu. Setiap proyek didampingi oleh seorang Dedicated Project Lead dengan sesi sync mingguan dan laporan progres transparan via Slack/WhatsApp.',
                },
                {
                  q: 'Bagaimana dukungan pasca peluncuran (post-launch)?',
                  a: 'Kami memberikan garansi pemeliharaan teknis dan asistensi penuh selama 60 hari setelah peluncuran untuk memastikan situs berjalan sempurna.',
                },
              ],
            },
          },
          {
            id: 'cta_agency',
            type: 'cta',
            props: {
              badge: 'Mulai Kolaborasi',
              title: 'Punya Proyek Menantang untuk Kami?',
              subtitle: 'Diskusikan ide dan visi Anda bersama tim strategi kami sekarang. Kami siap membantu brand Anda bersinar.',
              buttonText: 'Jadwalkan Konsultasi via WhatsApp',
              buttonLink: 'https://wa.me/6281234567890',
            },
          },
        ],
      };

    case 'saas':
      return {
        id: 'page_home',
        slug: 'home',
        title: siteIdentity.title || 'Cloud App & SaaS Platform - Otomatisasi Cerdas Modern',
        status: 'published',
        themeId: 'neve-startup',
        colorMode: 'light',
        mobileNavType: 'curved',
        header: {
          brandName: siteIdentity.title || 'Neve Cloud App',
          brandTagline: siteIdentity.tagline || 'Tingkatkan Produktivitas Tim Anda dengan Otomatisasi Cerdas',
          phone: '0812-3456-7890',
          whatsappNumber: '6281234567890',
          navLinks: [
            { label: 'Fitur Cloud', href: '#features' },
            { label: 'Modul Sistem', href: '#fleet' },
            { label: 'Paket Harga', href: '#pricing' },
            { label: 'Kisah Sukses', href: '#testimonials' },
            { label: 'FAQ', href: '#faq' },
            { label: 'Demo Produk', href: '/?contact=true' },
          ],
        },
        footer: {
          brandName: siteIdentity.title || 'Neve Cloud App',
          description: 'Platform orkestrasi workflow dan analitik bisnis modern berbasis cloud dengan keamanan enkripsi data enterprise dan SLA uptime 99.99%.',
          address: 'Mega Kuningan Cyber Tower 2 Lt. 18, Jakarta Selatan',
          phone: '0812-3456-7890',
          email: 'sales@nevecloud.io',
          copyright: `© ${year} ${siteIdentity.title || 'Neve Cloud App'}. Powered by Neve Startup Theme.`,
        },
        floatingWhatsapp: {
          enabled: true,
          phoneNumber: '6281234567890',
          agentName: 'Product Specialist',
          agentStatus: 'Online',
          greetingMessage: 'Halo! Ingin demonstrasi langsung atau uji coba gratis 14 hari?',
          defaultMessage: 'Halo Tim Sales SaaS, saya ingin jadwal demo dan informasi paket tim bisnis.',
          ctaText: 'Tanya Solusi Cloud',
        },
        seo: {
          metaTitle: `${siteIdentity.title || 'Neve Cloud App'} - Solusi Workflow & Otomatisasi Cloud`,
          metaDescription: 'Otomatisasikan alur kerja bisnis tim Anda dengan analitik realtime, integrasi API tanpa hambatan, dan keamanan data enterprise.',
          ogImage: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=1600',
          jsonLdType: 'SoftwareApplication',
          canonical: '',
        },
        blocks: [
          {
            id: 'hero_saas',
            type: 'hero-slider',
            props: {
              badge: 'Tema Resmi Neve • SaaS & Startup Digital',
              title: 'Otomatisasi Alur Kerja Pintar untuk Pertumbuhan Tim Cepat',
              subtitle: 'Tingkatkan produktivitas hingga 300% dengan platform terpusat yang menghubungkan analitik data, otomatisasi tugas, dan kolaborasi tim tanpa friksi.',
              ctaPrimaryText: 'Coba Gratis 14 Hari',
              ctaPrimaryLink: '#pricing',
              ctaSecondaryText: 'Jadwalkan Live Demo',
              ctaSecondaryLink: '/?contact=true',
              slides: [
                {
                  id: 's1',
                  badge: 'Cloud Orchestration Platform 2026',
                  title: 'Otomatisasi Alur Kerja Pintar untuk Pertumbuhan Tim Cepat',
                  subtitle: 'Tingkatkan produktivitas hingga 300% dengan platform terpusat yang menghubungkan analitik data, otomatisasi tugas, dan kolaborasi tim tanpa friksi.',
                  imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=1600',
                },
              ],
            },
          },
          {
            id: 'features_saas',
            type: 'features',
            props: {
              badge: 'Kapabilitas Platform Cloud',
              title: 'Dirancang Khusus untuk Kebutuhan Skalabilitas',
              subtitle: 'Fitur canggih yang mempermudah tim manajemen hingga developer bekerja selaras.',
              items: [
                { icon: 'shield-check', title: 'Real-Time Data Analytics', desc: 'Pantau metrik KPI, arus pendapatan, dan performa tim melalui dashboard visual interaktif.' },
                { icon: 'zap', title: 'Otomatisasi Task Tanpa Kode', desc: 'Bangun alur kerja pintar cukup dengan drag-and-drop antar aplikasi bisnis Anda.' },
                { icon: 'award', title: '100+ Integrasi API Terbuka', desc: 'Terhubung mulus dengan Slack, Google Workspace, Stripe, WhatsApp, dan sistem internal Anda.' },
                { icon: 'clock', title: 'Enkripsi Data Bank-Grade', desc: 'Keamanan standar SOC-2 Type II dan enkripsi AES-256 untuk proteksi privasi pelanggan.' },
              ],
            },
          },
          {
            id: 'catalog_saas',
            type: 'fleet-catalog',
            props: {
              badge: 'Modul & Layanan Aplikasi',
              title: 'Modul Unggulan Neve Cloud',
              subtitle: 'Solusi terpadu yang dapat diaktifkan sesuai skala operasional bisnis Anda.',
              catalogType: 'digital',
              items: [
                {
                  id: 'm1',
                  name: 'Centralized Metrics Dashboard',
                  brand: 'Neve Core',
                  category: 'Analytics',
                  pricePerDay: 'Included',
                  year: '2026',
                  transmission: 'Cloud Web',
                  fuel: 'Real-Time Streaming',
                  capacity: 'Unlimited KPIs',
                  rating: 5.0,
                  reviewsCount: 120,
                  image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&auto=format&fit=crop&q=80',
                  highlight: 'Core Module',
                  features: ['Visualisasi Grafik Dinamis', 'Export PDF & Excel Otomatis', 'Filter Multi-Dimensi', 'Notifikasi Anomali AI'],
                },
                {
                  id: 'm2',
                  name: 'Workflow Visual Automation Builder',
                  brand: 'Neve Flow',
                  category: 'Automation',
                  pricePerDay: 'Included',
                  year: '2026',
                  transmission: 'No-Code Engine',
                  fuel: 'Instant Trigger',
                  capacity: '10k Executions/day',
                  rating: 4.9,
                  reviewsCount: 94,
                  image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&auto=format&fit=crop&q=80',
                  highlight: 'Most Popular',
                  features: ['Drag and Drop Trigger & Action', 'Dukungan Conditional Branching', 'Retry Logic Otomatis', 'Audit Log Eksekusi'],
                },
                {
                  id: 'm3',
                  name: 'Omni-Channel Customer Data Sync',
                  brand: 'Neve Sync',
                  category: 'Integration',
                  pricePerDay: 'Included',
                  year: '2026',
                  transmission: 'Two-Way Sync',
                  fuel: 'Sub-second Sync',
                  capacity: '500k Contacts',
                  rating: 4.9,
                  reviewsCount: 81,
                  image: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=600&auto=format&fit=crop&q=80',
                  highlight: 'High Speed',
                  features: ['Sinkronisasi Dua Arah Instan', 'Pencegahan Data Duplikat', 'Field Mapping Fleksibel', 'Enkripsi Data At-Rest'],
                },
                {
                  id: 'm4',
                  name: 'Granular Access & Security Audit',
                  brand: 'Neve Shield',
                  category: 'Security',
                  pricePerDay: 'Enterprise',
                  year: '2026',
                  transmission: 'RBAC Policy',
                  fuel: 'SOC-2 Ready',
                  capacity: 'Role Management',
                  rating: 5.0,
                  reviewsCount: 47,
                  image: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=600&auto=format&fit=crop&q=80',
                  highlight: 'Bank Grade',
                  features: ['Single Sign-On (SAML / Okta)', 'Role-Based Access Control', 'Pencatatan Audit Trail Lengkap', 'IP Whitelisting'],
                },
                {
                  id: 'm5',
                  name: 'High-Throughput Webhook Pipeline',
                  brand: 'Neve API',
                  category: 'Developer',
                  pricePerDay: 'Included',
                  year: '2026',
                  transmission: 'REST & GraphQL',
                  fuel: '100% Uptime SLA',
                  capacity: '1M Requests/day',
                  rating: 4.8,
                  reviewsCount: 66,
                  image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&auto=format&fit=crop&q=80',
                  highlight: 'Dev Friendly',
                  features: ['REST API & GraphQL Endpoints', 'Webhook Event Subscriptions', 'Sandbox Testing Environment', 'Dokumentasi Interaktif'],
                },
                {
                  id: 'm6',
                  name: 'Real-Time Team Collaboration Hub',
                  brand: 'Neve Team',
                  category: 'Productivity',
                  pricePerDay: 'Included',
                  year: '2026',
                  transmission: 'Multi-User',
                  fuel: 'Instant Messaging',
                  capacity: 'Unlimited Teams',
                  rating: 4.9,
                  reviewsCount: 88,
                  image: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=600&auto=format&fit=crop&q=80',
                  highlight: 'Collaboration',
                  features: ['Shared Workspace & Catatan', 'Komentar Inline & Mention Tim', 'Integrasi Notifikasi WhatsApp', 'Riwayat Perubahan Terperinci'],
                },
              ],
            },
          },
          {
            id: 'pricing_saas',
            type: 'pricing',
            props: {
              badge: 'Investasi Terukur',
              title: 'Paket Berlangganan yang Tumbuh Bersama Anda',
              subtitle: 'Uji coba gratis 14 hari. Tidak memerlukan kartu kredit. Batalkan kapan saja.',
              plans: [
                {
                  name: 'Starter Plan',
                  price: 'Rp 149.000',
                  period: '/bulan',
                  description: 'Sempurna untuk tim kecil dan bisnis yang baru memulai otomatisasi.',
                  highlight: false,
                  features: ['Hingga 5 Anggota Tim', '1.000 Eksekusi Otomatisasi/bln', 'Dashboard Metrik Standar', 'Dukungan Komunitas & Email'],
                  buttonText: 'Mulai Uji Coba Gratis',
                },
                {
                  name: 'Growth Pro',
                  price: 'Rp 499.000',
                  period: '/bulan',
                  description: 'Paling diminati! Untuk perusahaan yang membutuhkan integrasi penuh.',
                  highlight: true,
                  features: ['Hingga 20 Anggota Tim', '50.000 Eksekusi Otomatisasi/bln', 'Akses Semua Integrasi API', 'Prioritas Customer Support 24/7', 'Analitik Prediktif AI'],
                  buttonText: 'Coba Growth Pro Gratis',
                },
                {
                  name: 'Enterprise Cloud',
                  price: 'Rp 1.999.000',
                  period: '/bulan',
                  description: 'Skalabilitas tinggi dengan kontrol keamanan mutlak dan dedicated server.',
                  highlight: false,
                  features: ['Pengguna Tidak Terbatas', 'Eksekusi Otomatisasi Unlimited', 'SLA Uptime 99.99%', 'Dedicated Account Manager', 'Keamanan SSO & Kustom Audit'],
                  buttonText: 'Hubungi Tim Enterprise',
                },
              ],
            },
          },
          {
            id: 'testimonials_saas',
            type: 'testimonials',
            props: {
              badge: 'Kisah Pelanggan',
              title: 'Dipercaya oleh Tim Berkinerja Tinggi',
              subtitle: 'Bagaimana platform kami membantu berbagai skala bisnis menghemat ribuan jam kerja.',
              reviews: [
                {
                  name: 'Raditya Pratama',
                  role: 'Head of Operations di Logistik Nasional',
                  rating: 5,
                  comment: 'Neve SaaS membantu kami mengotomatisasi alur penugasan kurir secara instan. Kesalahan input manual berkurang hingga 95%.',
                  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop',
                },
                {
                  name: 'Kartika Sari',
                  role: 'VP of Engineering di EdTech Platform',
                  rating: 5,
                  comment: 'Integrasi API-nya sangat mudah diimplementasikan. Dalam 2 hari seluruh sistem kami sudah tersinkronisasi tanpa hambatan.',
                  avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&h=100&fit=crop',
                },
                {
                  name: 'Farhan Setiawan',
                  role: 'Tech Lead di Digital Healthcare',
                  rating: 5,
                  comment: 'Kecepatan pemuatan dan stabilitas sistem luar biasa. Desain light-nya sangat bersih dan nyaman digunakan seharian penuh.',
                  avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
                },
              ],
            },
          },
          {
            id: 'faq_saas',
            type: 'faq',
            props: {
              badge: 'Informasi Layanan',
              title: 'Pertanyaan Seputar Uji Coba & Implementasi',
              subtitle: 'Semua jawaban yang Anda butuhkan untuk memulai migrasi ke Neve Cloud.',
              faqs: [
                {
                  q: 'Bagaimana cara memulai masa uji coba 14 hari?',
                  a: 'Cukup pilih paket yang sesuai dan hubungi admin kami untuk aktivasi akun uji coba instan tanpa perlu memasukkan kartu kredit.',
                },
                {
                  q: 'Apakah data bisnis kami aman di platform ini?',
                  a: 'Sangat aman. Seluruh data dienkripsi dengan standar AES-256 baik saat transit maupun at-rest pada data center tersertifikasi ISO 27001.',
                },
                {
                  q: 'Bisakah tim kami dibantu proses migrasi data dari sistem lama?',
                  a: 'Ya, tim Customer Success kami siap mendampingi proses impor data CSV/JSON dan pengaturan alur kerja otomatisasi tanpa biaya tambahan.',
                },
              ],
            },
          },
          {
            id: 'cta_saas',
            type: 'cta',
            props: {
              badge: 'Siap Mengakselerasi Tim Anda?',
              title: 'Mulai Uji Coba Gratis 14 Hari Sekarang',
              subtitle: 'Bergabunglah bersama ribuan tim cerdas yang telah mentransformasi cara kerja mereka dengan Neve Cloud Platform.',
              buttonText: 'Aktivasi Uji Coba via WhatsApp',
              buttonLink: 'https://wa.me/6281234567890',
            },
          },
        ],
      };

    case 'rental':
      return {
        id: 'page_home',
        slug: 'home',
        title: siteIdentity.title || 'Rental Kendaraan & Transportasi VIP - Armada Terawat 24 Jam',
        status: 'published',
        themeId: 'oceanwp-store',
        colorMode: 'light',
        mobileNavType: 'curved',
        header: {
          brandName: siteIdentity.title || 'Samudera VIP Transport',
          brandTagline: siteIdentity.tagline || 'Armada Terawat, Bersih & Layanan Pelanggan 24 Jam Terpercaya',
          phone: '0812-3456-7890',
          whatsappNumber: '6281234567890',
          navLinks: [
            { label: 'Pilihan Armada', href: '#fleet' },
            { label: 'Keunggulan', href: '#features' },
            { label: 'Paket Sewa', href: '#pricing' },
            { label: 'Testimoni', href: '#testimonials' },
            { label: 'FAQ', href: '#faq' },
            { label: 'Kontak', href: '/?contact=true' },
          ],
        },
        footer: {
          brandName: siteIdentity.title || 'Samudera VIP Transport',
          description: 'Pusat sewa mobil terpercaya dengan armada bersih, supir berpengalaman ramah, dan layanan antar jemput bandara 24 jam nonstop.',
          address: 'Kawasan Bandara Soekarno Hatta Terminal 3 & Jl. TB Simatupang, Jakarta',
          phone: '0812-3456-7890',
          email: 'booking@samuderarental.com',
          copyright: `© ${year} ${siteIdentity.title || 'Samudera VIP Transport'}. Powered by OceanWP Theme.`,
        },
        floatingWhatsapp: {
          enabled: true,
          phoneNumber: '6281234567890',
          agentName: 'Customer Care 24 Jam',
          agentStatus: 'Online 24 Jam',
          greetingMessage: 'Halo! Butuh sewa mobil atau tanya ketersediaan unit hari ini? Hubungi kami langsung.',
          defaultMessage: 'Halo Admin, saya ingin reservasi/tanya ketersediaan armada mobil.',
          ctaText: 'Chat WhatsApp',
        },
        seo: {
          metaTitle: `${siteIdentity.title || 'Samudera VIP Transport'} - Sewa Mobil Mewah Jakarta`,
          metaDescription: 'Rental mobil mewah Alphard, Innova Zenix, Fortuner, dan HiAce dengan supir ramah bergaransi tepat waktu.',
          ogImage: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?q=80&w=1600',
          jsonLdType: 'AutoRental',
          canonical: '',
        },
        blocks: [
          {
            id: 'hero_rental',
            type: 'hero-slider',
            props: {
              badge: 'Tema Resmi OceanWP • Rental Kendaraan VIP',
              title: 'Perjalanan Nyaman & Elegan dengan Armada Terbaik',
              subtitle: 'Unit terbaru, kabin harum dan bersih, supir ramah berpengalaman, dan siap melayani rute dalam maupun luar kota kapan saja.',
              ctaPrimaryText: 'Pilih Armada Mobil',
              ctaPrimaryLink: '#fleet',
              ctaSecondaryText: 'Reservasi WhatsApp 24 Jam',
              ctaSecondaryLink: 'https://wa.me/6281234567890',
              slides: [
                {
                  id: 's1',
                  badge: 'Unit Terawat • Siap Berangkat',
                  title: 'Perjalanan Nyaman & Elegan dengan Armada Terbaik',
                  subtitle: 'Unit terbaru, kabin harum dan bersih, supir ramah berpengalaman, dan siap melayani rute dalam maupun luar kota kapan saja.',
                  imageUrl: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?q=80&w=1600',
                },
              ],
            },
          },
          {
            id: 'features_rental',
            type: 'features',
            props: {
              badge: 'Standar Pelayanan VIP',
              title: 'Keunggulan Rental Bersama Samudera Transport',
              subtitle: 'Fokus pada kenyamanan, keselamatan, dan ketepatan waktu penjemputan Anda.',
              items: [
                { icon: 'shield-check', title: 'Unit Bersih & Terawat', desc: 'Perawatan berkala di bengkel resmi dan desinfeksi kabin sebelum keberangkatan.' },
                { icon: 'zap', title: 'Supir Ramah Berpengalaman', desc: 'Mengenal rute tercepat dan terlatih melayani tamu VIP dengan sopan santun.' },
                { icon: 'award', title: 'Asuransi All-Risk Termasuk', desc: 'Perjalanan Anda dilindungi proteksi asuransi menyeluruh tanpa rasa khawatir.' },
                { icon: 'clock', title: 'Bebas Antar-Jemput Bandara', desc: 'Layanan tepat waktu di Terminal Bandara atau langsung ke lobi hotel Anda.' },
              ],
            },
          },
          {
            id: 'catalog_rental',
            type: 'fleet-catalog',
            props: {
              badge: 'Pilihan Kendaraan',
              title: 'Daftar Armada Rental Paling Populer',
              subtitle: 'Pilih unit sesuai kebutuhan perjalanan keluarga, wisata, maupun kunjungan bisnis.',
              catalogType: 'rental',
              vehicles: [
                {
                  id: 'v1',
                  name: 'Toyota Alphard Transformer VIP',
                  brand: 'Toyota',
                  category: 'Luxury MPV',
                  pricePerDay: 'Rp 2.500.000',
                  priceDriver: 'Rp 2.800.000',
                  year: '2025',
                  transmission: 'Automatic',
                  fuel: 'Bensin',
                  capacity: '6 Penumpang VIP',
                  rating: 5.0,
                  reviewsCount: 180,
                  image: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=600&auto=format&fit=crop&q=80',
                  highlight: 'Paling Diminati Tamu VIP',
                  features: ['Pilot Seat Full Leather', 'Sunroof & Ambient Light', 'Supir Jas Rapi Profesional', 'Air Mineral & Wifi Gratis'],
                },
                {
                  id: 'v2',
                  name: 'Toyota Innova Zenix Hybrid',
                  brand: 'Toyota',
                  category: 'Comfort MPV',
                  pricePerDay: 'Rp 850.000',
                  priceDriver: 'Rp 1.100.000',
                  year: '2025',
                  transmission: 'Automatic',
                  fuel: 'Hybrid Irit',
                  capacity: '7 Penumpang',
                  rating: 4.9,
                  reviewsCount: 142,
                  image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=600&auto=format&fit=crop&q=80',
                  highlight: 'Paling Irit & Nyaman',
                  features: ['Kabin Luas & Senyap', 'Panoramic Roof', 'Suspensi Empuk Zenix', 'Pendingin Kabin Dobel Blower'],
                },
                {
                  id: 'v3',
                  name: 'Toyota Fortuner 2.8 GR Sport',
                  brand: 'Toyota',
                  category: 'Executive SUV',
                  pricePerDay: 'Rp 1.300.000',
                  priceDriver: 'Rp 1.550.000',
                  year: '2025',
                  transmission: 'Automatic',
                  fuel: 'Diesel Turbo',
                  capacity: '7 Penumpang',
                  rating: 4.9,
                  reviewsCount: 95,
                  image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=600&auto=format&fit=crop&q=80',
                  highlight: 'Gagah & Bertenaga',
                  features: ['Mesin Diesel 2800cc Bertenaga', 'Body Kit GR Sport Asli', 'Jok Kulit Hitam Sporty', 'Siap Luar Kota Segala Medan'],
                },
                {
                  id: 'v4',
                  name: 'Toyota HiAce Premio Luxury',
                  brand: 'Toyota',
                  category: 'VIP Commuter',
                  pricePerDay: 'Rp 1.600.000',
                  priceDriver: 'Rp 1.900.000',
                  year: '2025',
                  transmission: 'Manual',
                  fuel: 'Diesel',
                  capacity: '10 Penumpang',
                  rating: 4.9,
                  reviewsCount: 78,
                  image: 'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=600&auto=format&fit=crop&q=80',
                  highlight: 'Keluarga & Rombongan',
                  features: ['Captain Seat Khusus', 'Audio Karaoke & Smart TV', 'Legroom Sangat Lapang', 'Bagasi Ekstra Besar'],
                },
                {
                  id: 'v5',
                  name: 'Honda CR-V Turbo Prestige',
                  brand: 'Honda',
                  category: 'Compact SUV',
                  pricePerDay: 'Rp 1.100.000',
                  priceDriver: 'Rp 1.350.000',
                  year: '2025',
                  transmission: 'Automatic',
                  fuel: 'Bensin Turbo',
                  capacity: '7 Penumpang',
                  rating: 4.8,
                  reviewsCount: 62,
                  image: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=600&auto=format&fit=crop&q=80',
                  highlight: 'Elegan Modern',
                  features: ['Honda Sensing Lengkap', 'Sunroof Panoramic', 'Audio BOSE Premium', 'Desain Modern Terkini'],
                },
                {
                  id: 'v6',
                  name: 'Mitsubishi Pajero Sport Dakar',
                  brand: 'Mitsubishi',
                  category: 'Executive SUV',
                  pricePerDay: 'Rp 1.250.000',
                  priceDriver: 'Rp 1.500.000',
                  year: '2025',
                  transmission: 'Automatic',
                  fuel: 'Diesel',
                  capacity: '7 Penumpang',
                  rating: 4.9,
                  reviewsCount: 84,
                  image: 'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=600&auto=format&fit=crop&q=80',
                  highlight: 'Tangguh Berkelas',
                  features: ['Transmisi 8-Speed Halus', 'Suspensi Stabil Nyaman', 'Interior Mewah Rapi', 'AC Digital Dingin Merata'],
                },
              ],
            },
          },
          {
            id: 'pricing_rental',
            type: 'pricing',
            props: {
              badge: 'Tarif Sewa Transparan',
              title: 'Paket Rental Fleksibel Sesuai Kebutuhan Anda',
              subtitle: 'Harga tertera sudah termasuk perlindungan asuransi dan jaminan unit pengganti jika ada kendala.',
              plans: [
                {
                  name: 'Paket Lepas Kunci',
                  price: 'Mulai Rp 450.000',
                  period: '/24 jam',
                  description: 'Kebebasan berkendara mandiri dengan persyaratan verifikasi cepat.',
                  highlight: false,
                  features: ['Durasi 24 Jam Penuh', 'Asuransi All-Risk Termasuk', 'Unit Bersih Siap Pakai', 'Bebas Kilometer Dalam Kota'],
                  buttonText: 'Sewa Lepas Kunci',
                },
                {
                  name: 'Paket All-In Supir & BBM',
                  price: 'Mulai Rp 850.000',
                  period: '/12 jam',
                  description: 'Paling diminati! Duduk tenang tanpa lelah, supir kami yang mengemudi.',
                  highlight: true,
                  features: ['Mobil + Supir Profesional', 'Sudah Termasuk BBM', 'Bebas Antar Jemput Bandara/Hotel', 'Bantuan Angkat Koper & Bagasi', 'Air Mineral Dingin Tersedia'],
                  buttonText: 'Pilih Paket All-In',
                },
                {
                  name: 'Paket Bulanan Korporasi',
                  price: 'Hubungi Kami',
                  period: '/bulan',
                  description: 'Solusi operasional kendaraan dinas perusahaan dengan fasilitas servis berkala.',
                  highlight: false,
                  features: ['Unit Baru Tahun Berjalan', 'Maintenance & Servis Gratis', 'Mobil Pengganti Instan 1x24 Jam', 'Faktur Pajak Perusahaan Resmi'],
                  buttonText: 'Konsultasi Korporasi',
                },
              ],
            },
          },
          {
            id: 'testimonials_rental',
            type: 'testimonials',
            props: {
              badge: 'Pengalaman Pelanggan',
              title: 'Ulasan Nyata dari Para Penyewa Kami',
              subtitle: 'Kepuasan dan kenyamanan perjalanan Anda adalah prioritas nomor satu kami.',
              reviews: [
                {
                  name: 'Agus Pramono',
                  role: 'Direktur Keuangan - Kunjungan Kerja Jakarta',
                  rating: 5,
                  comment: 'Supir Pak Joko sangat tepat waktu menjemput di Terminal 3 Bandara Soetta. Unit Alphard-nya wangi sekali dan bersih seperti baru keluar dari showroom.',
                  avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
                },
                {
                  name: 'Dr. Maya Anggraeni',
                  role: 'Penyewa Keluarga - Wisata Bandung',
                  rating: 5,
                  comment: 'Sewa Innova Zenix 3 hari bersama keluarga besar. Mobilnya sangat irit dan suspensinya empuk. Anak-anak tidur pulas sepanjang perjalanan.',
                  avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&h=100&fit=crop',
                },
                {
                  name: 'Rian Ardiansyah',
                  role: 'Event Organizer Wedding Jakarta',
                  rating: 5,
                  comment: 'Sudah langganan lebih dari 2 tahun untuk mobil pengantin dan tamu VIP. Tidak pernah mengecewakan. Respon admin WhatsApp selalu kilat.',
                  avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop',
                },
              ],
            },
          },
          {
            id: 'faq_rental',
            type: 'faq',
            props: {
              badge: 'Informasi Penting',
              title: 'Pertanyaan yang Kerap Diajukan Penyewa',
              subtitle: 'Ketahui syarat dan ketentuan sewa kendaraan dengan jelas dan transparan.',
              faqs: [
                {
                  q: 'Apa saja syarat untuk sewa mobil lepas kunci?',
                  a: 'Cukup melampirkan foto KTP, SIM A yang masih berlaku, serta bukti reservasi tiket pesawat atau voucher hotel (untuk tamu luar kota). Proses verifikasi cepat hanya butuh 15 menit.',
                },
                {
                  q: 'Apakah bisa melakukan penjemputan di Bandara Soekarno Hatta malam hari?',
                  a: 'Bisa! Layanan kami beroperasi 24 jam nonstop. Supir kami siap standby di lobi kedatangan bandara sesuai nomor penerbangan Anda.',
                },
                {
                  q: 'Bagaimana jika terjadi kerusakan pada mobil saat perjalanan?',
                  a: 'Seluruh armada kami telah dilindungi asuransi All-Risk resmi. Jika terjadi kendala mesin, tim mekanik kami akan segera meluncur atau menyediakan unit pengganti dalam 1 jam.',
                },
              ],
            },
          },
          {
            id: 'cta_rental',
            type: 'cta',
            props: {
              badge: 'Ketersediaan Terbatas',
              title: 'Booking Unit Kendaraan Anda Sekarang Sebelum Penuh',
              subtitle: 'Ketersediaan armada terbatas terutama di akhir pekan dan musim liburan. Hubungi tim reservasi kami untuk penawaran harga spesial hari ini.',
              buttonText: 'Chat WhatsApp Reservasi',
              buttonLink: 'https://wa.me/6281234567890',
            },
          },
        ],
      };

    case 'custom':
    default:
      return {
        id: 'page_home',
        slug: 'home',
        title: siteIdentity.title || 'The Chronicle & Essays - Jurnal Editorial Modern',
        status: 'published',
        themeId: 'twenty-twenty-five',
        colorMode: 'light',
        mobileNavType: 'curved',
        header: {
          brandName: siteIdentity.title || 'The Chronicle & Essays',
          brandTagline: siteIdentity.tagline || 'Editorial Gutenberg Edition',
          phone: '0812-3456-7890',
          whatsappNumber: '6281234567890',
          navLinks: [
            { label: 'Berita Utama', href: '#features' },
            { label: 'Esai Budaya', href: '#articles' },
            { label: 'Kolom Opini', href: '#testimonials' },
            { label: 'Paket Langganan', href: '#pricing' },
            { label: 'FAQ', href: '#faq' },
            { label: 'Kontak', href: '/?contact=true' },
          ],
        },
        footer: {
          brandName: siteIdentity.title || 'The Chronicle & Essays',
          description: 'Publikasi editorial digital independen yang menyajikan esai mendalam, wawasan teknologi cerdas, dan kajian budaya kontemporer.',
          address: 'Jl. Raden Saleh No. 12, Menteng, Jakarta Pusat',
          phone: '0812-3456-7890',
          email: 'redaksi@thechronicle.id',
          copyright: `© ${year} ${siteIdentity.title || 'The Chronicle & Essays'}. Diterbitkan dengan standar Gutenberg WordPress 6.7.`,
        },
        floatingWhatsapp: {
          enabled: true,
          phoneNumber: '6281234567890',
          agentName: 'Redaksi Editorial',
          agentStatus: 'Online',
          greetingMessage: 'Halo! Ingin mengirimkan naskah esai atau kerja sama publikasi?',
          defaultMessage: 'Halo Redaksi, saya ingin bertanya seputar pengiriman naskah dan kemitraan konten.',
          ctaText: 'Kontak Redaksi',
        },
        seo: {
          metaTitle: `${siteIdentity.title || 'The Chronicle & Essays'} - Jurnal Editorial & Wawasan`,
          metaDescription: 'Publikasi esai mendalam, analisis budaya, dan perkembangan sains dengan tata letak tipografi editorial modern.',
          ogImage: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?q=80&w=1600',
          jsonLdType: 'NewsArticle',
          canonical: '',
        },
        blocks: [
          {
            id: 'hero_editorial',
            type: 'hero-slider',
            props: {
              badge: 'Tema Resmi Twenty Twenty-Five • Siap Pakai',
              title: 'Masa Depan Tipografi Digital & Jurnalisme Modern',
              subtitle: 'Menghadirkan ketenangan bagi pembaca dengan ruang lapang, tipografi terstruktur, dan pemuatan artikel berkecepatan tinggi.',
              ctaPrimaryText: 'Mulai Membaca Esai',
              ctaPrimaryLink: '#articles',
              ctaSecondaryText: 'Hubungi Redaksi',
              ctaSecondaryLink: '/?contact=true',
              slides: [
                {
                  id: 's1',
                  badge: 'Edisi Khusus • WordPress 6.7',
                  title: 'Masa Depan Tipografi Digital & Jurnalisme Modern',
                  subtitle: 'Menghadirkan ketenangan bagi pembaca dengan ruang lapang, tipografi terstruktur, dan pemuatan artikel berkecepatan tinggi.',
                  imageUrl: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?q=80&w=1600',
                },
              ],
            },
          },
          {
            id: 'features_editorial',
            type: 'features',
            props: {
              badge: 'Pilar Jurnalisme Kami',
              title: 'Komitmen pada Kejernihan & Kualitas Informasi',
              subtitle: 'Setiap artikel disusun melalui riset mendalam dan standar penyuntingan profesional.',
              items: [
                { icon: 'shield-check', title: 'Riset Terverifikasi', desc: 'Fakta dan data yang disajikan melalui proses konfirmasi independen.' },
                { icon: 'zap', title: 'Loading Cepat Tanpa Iklan', desc: 'Pengalaman membaca nyaman tanpa gangguan banner berkedip atau pop-up.' },
                { icon: 'award', title: 'Penulis Berpengalaman', desc: 'Ditulis oleh pakar industri, jurnalis senior, dan akademisi kredibel.' },
                { icon: 'clock', title: 'Kurasi Rutin Mingguan', desc: 'Rangkuman artikel esensial dikirimkan setiap pekan langsung ke inbox Anda.' },
              ],
            },
          },
          {
            id: 'articles_editorial',
            type: 'articles',
            props: {
              badge: 'Arsip Tulisan Terkini',
              title: 'Esai & Laporan Mendalam Minggu Ini',
              subtitle: 'Kumpulan pemikiran terbaik seputar desain, teknologi cerdas, dan perkembangan sosial masyarakat.',
            },
          },
          {
            id: 'pricing_editorial',
            type: 'pricing',
            props: {
              badge: 'Dukung Jurnalisme Independen',
              title: 'Pilihan Langganan Keanggotaan Pembaca',
              subtitle: 'Bantu kami menjaga independensi jurnalisme dan nikmati kurasi tulisan eksklusif tanpa iklan.',
              plans: [
                {
                  name: 'Pembaca Bebas',
                  price: 'Gratis',
                  period: '/selamanya',
                  description: 'Akses penuh ke semua artikel publik dan newsletter mingguan reguler.',
                  highlight: false,
                  features: ['Akses Semua Artikel Publik', 'Newsletter Mingguan', 'Komentar Komunitas'],
                  buttonText: 'Daftar Gratis',
                },
                {
                  name: 'Anggota Komunitas',
                  price: 'Rp 49.000',
                  period: '/bulan',
                  description: 'Paling diminati! Akses esai mendalam dan arsip eksklusif jurnal tahunan.',
                  highlight: true,
                  features: ['Semua Fitur Gratis', 'Esai Khusus Member', 'Diskusi Tertutup Bulanan', 'Format Baca E-Book PDF', 'Bebas Iklan 100%'],
                  buttonText: 'Gabung Member',
                },
                {
                  name: 'Patron Supporter',
                  price: 'Rp 149.000',
                  period: '/bulan',
                  description: 'Dukungan penuh untuk program beasiswa jurnalisme dan riset investigatif.',
                  highlight: false,
                  features: ['Semua Fitur Member', 'Nama Tercantum di Halaman Patron', 'Undangan Diskusi Redaksi', 'Akses Lebih Awal ke Buku Esai'],
                  buttonText: 'Dukung sebagai Patron',
                },
              ],
            },
          },
          {
            id: 'testimonials_editorial',
            type: 'testimonials',
            props: {
              badge: 'Apresiasi Pembaca',
              title: 'Apa Kata Para Penulis & Akademisi?',
              subtitle: 'Tanggapan dari komunitas pembaca setia kami.',
              reviews: [
                {
                  name: 'Dr. Adrian Maulana',
                  role: 'Dosen Komunikasi Digital',
                  rating: 5,
                  comment: 'Tata letak Twenty Twenty-Five memberikan ruang bernapas yang sangat dibutuhkan dalam membaca analisis panjang. Sangat elegan.',
                  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop',
                },
                {
                  name: 'Siti Rahmawati',
                  role: 'Peneliti Sosial Budaya',
                  rating: 5,
                  comment: 'Kombinasi tipografi yang tajam dan kontras warna yang ramah di mata membuat sesi membaca menjadi pengalaman yang menenangkan.',
                  avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=100&h=100&fit=crop',
                },
                {
                  name: 'Bambang Sutejo',
                  role: 'Esais & Kolumnis Independen',
                  rating: 5,
                  comment: 'Sangat senang melihat platform CMS yang menghargai kekuatan kata-kata dan tipografi murni tanpa gangguan elemen norak.',
                  avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
                },
              ],
            },
          },
          {
            id: 'faq_editorial',
            type: 'faq',
            props: {
              badge: 'Informasi Redaksi',
              title: 'Pertanyaan Seputar Pengiriman Esai & Publikasi',
              subtitle: 'Ketahui pedoman kontribusi dan alur kurasi naskah di platform kami.',
              faqs: [
                {
                  q: 'Bagaimana cara mengirimkan esai atau opini ke redaksi?',
                  a: 'Anda dapat mengirimkan naskah berformat dokumen melalui email redaksi@thechronicle.id atau chat langsung ke kontak redaksi kami.',
                },
                {
                  q: 'Apakah naskah yang dimuat akan mendapatkan honorarium?',
                  a: 'Ya, seluruh tulisan yang lolos proses penyuntingan dan diterbitkan di rubrik utama akan mendapatkan kompensasi profesional.',
                },
                {
                  q: 'Apakah artikel dapat dibaca secara offline?',
                  a: 'Ya, situs ini didukung teknologi PWA sehingga artikel yang pernah Anda buka dapat diakses kembali bahkan saat tidak ada koneksi internet.',
                },
              ],
            },
          },
          {
            id: 'cta_editorial',
            type: 'cta',
            props: {
              badge: 'Komunitas Pembaca Cerdas',
              title: 'Bergabunglah Bersama 10.000+ Pembaca Setia Kami',
              subtitle: 'Dapatkan rangkuman mingguan artikel esensial pilihan langsung di inbox email Anda secara cuma-cuma.',
              buttonText: 'Hubungi Redaksi via WhatsApp',
              buttonLink: 'https://wa.me/6281234567890',
            },
          },
        ],
      };
  }
}
